ITEM_MAPPING = {
    -- Regions
    [1] = {"scholar", "toggle"},
    [2] = {"arsenal", "toggle"},
    [3] = {"darkhouse", "toggle"},
    [4] = {"churchmouse", "toggle"},
    [5] = {"lakeside", "toggle"},
    [6] = {"palekeep", "toggle"},
    [7] = {"moonlit", "toggle"},

    -- Classes
    [8] = {"wizard", "toggle"},
    [9] = {"assassin", "toggle"},
    [10] = {"heavyblade", "toggle"},
    [11] = {"dancer", "toggle"},
    [12] = {"druid", "toggle"},
    [13] = {"spellsword", "toggle"},
    [14] = {"sniper", "toggle"},
    [15] = {"bruiser", "toggle"},
    [16] = {"defender", "toggle"},
    [17] = {"ancient", "toggle"},

    -- Item sets
    [18] = {"arcane_set", "toggle"},
    [19] = {"night_set", "toggle"},
    [20] = {"timespace_set", "toggle"},
    [21] = {"wind_set", "toggle"},
    [22] = {"bloodwolf_set", "toggle"},
    [23] = {"assassin_set", "toggle"},
    [24] = {"rockdragon_set", "toggle"},
    [25] = {"flame_set", "toggle"},
    [26] = {"gem_set", "toggle"},
    [27] = {"lightning_set", "toggle"},
    [28] = {"shrine_set", "toggle"},
    [29] = {"lucky_set", "toggle"},
    [30] = {"life_set", "toggle"},
    [31] = {"poison_set", "toggle"},
    [32] = {"depth_set", "toggle"},
    [33] = {"darkbite_set", "toggle"},
    [34] = {"timegem_set", "toggle"},
    [35] = {"youkai_set", "toggle"},
    [36] = {"haunted_set", "toggle"},
    [37] = {"gladiator_set", "toggle"},
    [38] = {"sparkblade_set", "toggle"},
    [39] = {"swiftflight_set", "toggle"},
    [40] = {"sacredflame_set", "toggle"},
    [41] = {"ruins_set", "toggle"},
    [42] = {"lakeshrine_set", "toggle"},

    -- Upgrades
    [43] = {"emerald_upgrade", "toggle"},
    [44] = {"garnet_upgrade", "toggle"},
    [45] = {"ruby_upgrade", "toggle"},
    [46] = {"sapphire_upgrade", "toggle"},
    [47] = {"opal_upgrade", "toggle"},
    [48] = {"emerald_primary", "toggle"},
    [49] = {"garnet_primary", "toggle"},
    [50] = {"ruby_primary", "toggle"},
    [51] = {"sapphire_primary", "toggle"},
    [52] = {"opal_primary", "toggle"},
    [53] = {"emerald_secondary", "toggle"},
    [54] = {"garnet_secondary", "toggle"},
    [55] = {"ruby_secondary", "toggle"},
    [56] = {"sapphire_secondary", "toggle"},
    [57] = {"opal_secondary", "toggle"},
    [58] = {"emerald_special", "toggle"},
    [59] = {"garnet_special", "toggle"},
    [60] = {"ruby_special", "toggle"},
    [61] = {"sapphire_special", "toggle"},
    [62] = {"opal_special", "toggle"},
    [63] = {"emerald_defensive", "toggle"},
    [64] = {"garnet_defensive", "toggle"},
    [65] = {"ruby_defensive", "toggle"},
    [66] = {"sapphire_defensive", "toggle"},
    [67] = {"opal_defensive", "toggle"},

    -- Potions    
    [68] = {"full_heal_potion", "toggle"},
    [69] = {"level_up_potion", "toggle"},
    [70] = {"regen_potion", "toggle"},
    [71] = {"essence_of_spell", "toggle"},
    [72] = {"darkness_potion", "toggle"},
    [73] = {"quickening_potion", "toggle"},
    [74] = {"winged_potion", "toggle"},
    [75] = {"essence_of_wit", "toggle"},
    [76] = {"swifthand_potion", "toggle"},
    [77] = {"fire_potion", "toggle"},
    [78] = {"essence_of_strength", "toggle"},
    [79] = {"golden_potion", "toggle"},
    [80] = {"luck_potion", "toggle"},
    [81] = {"essence_of_steel", "toggle"},
    [82] = {"evasion_potion", "toggle"},
    [83] = {"longarm_potion", "toggle"},
    [84] = {"vitality_potion", "toggle"},

    -- Victory
    [85] = {"victory_wizard", "toggle"},
    [86] = {"victory_assassin", "toggle"},
    [87] = {"victory_heavyblade", "toggle"},
    [88] = {"victory_dancer", "toggle"},
    [89] = {"victory_druid", "toggle"},
    [90] = {"victory_spellsword", "toggle"},
    [91] = {"victory_sniper", "toggle"},
    [92] = {"victory_bruiser", "toggle"},
    [93] = {"victory_defender", "toggle"},
    [94] = {"victory_ancient", "toggle"},

    -- Other
    [95] = {"progressive_area", "consumable"},
    [96] = {"xp", "consumable"},
    [97] = {"treasuresphere", "consumable"},

    -- Fillers
    [98] = {"gold", "consumable"},
}