LOOT_MAPPING =
{
    ["arcane_set"] = "1",
    ["night_set"] = "1",
    ["timespace_set"] = "2",
    ["wind_set"] = "2",
    ["bloodwolf_set"] = "3",
    ["assassin_set"] = "3",
    ["rockdragon_set"] = "4",
    ["flame_set"] = "4",
    ["gem_set"] = "5",
    ["lightning_set"] = "5",
    ["shrine_set"] = "6",
    ["lucky_set"] = "6",
    ["life_set"] = "7",
    ["poison_set"] = "7",
    ["depth_set"] = "8",
    ["darkbite_set"] = "8",
    ["timegem_set"] = "9",
    ["youkai_set"] = "9",
    ["haunted_set"] = "10",
    ["gladiator_set"] = "10",
    ["sparkblade_set"] = "11",
    ["swiftflight_set"] = "11",
    ["sacredflame_set"] = "12",
    ["ruins_set"] = "12",
    ["lakeshrine_set"] = "13",
}